FROM centos:centos7.5.1804 as build
LABEL maintainer="<song.wu@xuncetech.com>" \
      name="xone-cplus-dev" \
      author="song.wu" \
      version="v1.0.4" \
      systemver="Centos7.5" \
      desc="xone cplus env" \
      build-date="20200429"
COPY 3rd_src.tar.gz /tmp/3rd_src.tar.gz

RUN set +x && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && yum install epel-release -y \
    && yum install centos-release-scl -y \
    && yum install devtoolset-7-make devtoolset-7-gcc devtoolset-7-gcc-c++ devtoolset-7-gdb libtool boost-devel openssl-devel file libuv-devel cmake3 c-ares-devel c-ares which ant cppunit-devel glog-devel leveldb-devel libatomic unzip gflags-devel -y \
    && ln -sf /usr/lib64/libatomic.so.1 /usr/lib64/libatomic.so \
    && scl enable devtoolset-7 bash \
    && echo "source /opt/rh/devtoolset-7/enable" >> /root/.bashrc \
    && source /root/.bashrc \
    && ln -sf /usr/bin/cmake3 /usr/bin/cmake \
    && cd /tmp \
    && tar -zxf 3rd_src.tar.gz && cd 3rd_src \
    && yum localinstall *.rpm -y \
    && tar -zxf hiredis-0.14.0.tar.gz && cd hiredis-0.14.0 && make -j16 && make install && cd .. \
    && tar -zxf jsoncpp-1.8.0.tar.gz && cd jsoncpp-1.8.0 && cmake -DCMAKE_BUILD_TYPE=release -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/usr/ . && make -j16 && make install && cd ..\
    && tar -zxf libzmq-4.2.1.tar.gz && cd libzmq-4.2.1 && ./autogen.sh && ./configure --prefix=/usr && make -j16 && make install && cd .. \
    && tar -zxf protobuf-3.2.1.tar.gz && cd protobuf-3.2.1 && ./autogen.sh && ./configure --prefix=/usr --libdir=/usr/lib64 && make -j16 && make install && cd .. \
    && tar -zxf QuantLib-1.16.tar.gz && cd QuantLib-1.16 && ./autogen.sh && ./configure --prefix=/usr && make -j16 && make install && cd .. \
    && tar -zxf spdlog-1.1.0.tar.gz && cd spdlog-1.1.0 && cmake -DCMAKE_INSTALL_PREFIX=/usr . && make -j16 && make install && cd ..\
    && tar -zxf tinyxml2-7.0.0.tar.gz && cd tinyxml2-7.0.0 && cmake -DCMAKE_INSTALL_PREFIX=/usr . && make -j16 && make install && cd ..\
    && tar -zxf uWebSockets-0.14.10.tar.gz && cd uWebSockets-0.14.10 && cmake . && make -j16 && make install && cd ..\
    && tar -zxf xlslib-2.4.0.tar.gz && cd xlslib-2.4.0 && sed -i '80s/CCLD/CXXLD/' ./targets/test/Makefile.in && ./configure --prefix=/usr && make -j16 && make install && cd .. \ 
    && tar -zxf BRPC-0.9.5.tar.gz && cd BRPC-0.9.5 && sh config_brpc.sh --headers=/usr/include --libs=/usr/lib64 --with-glog && make -j16 && cp -rf ./output/bin/* /usr/bin/ && cp -rf ./output/include/* /usr/include/ && cp -rf ./output/lib/* /usr/lib/ && cd .. \
    && tar -zxf zookeeper-release-3.5.5.tar.gz && cd zookeeper-release-3.5.5 && ant compile_jute && cd zookeeper-client/zookeeper-client-c && autoreconf -if && ./configure --prefix=/usr && make -j16 && make install  \
    && yum install libcurl-devel zlib-devel libuuid-devel -y \
    && rpm -ivh https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm \
    && yum install --enablerepo=mysql80-community --disablerepo=mysql56-community mysql-community-devel -y \ 
    && sed -i '1034s/[<>]/"/g' /usr/include/mysql/mysql_com.h \
    && ldconfig \
    && rm -f /usr/lib/libQuantLib.a \
    && rm -f /usr/lib/libbrpc.a \
    && rm -f /usr/lib/libzmq.a \
    && rm -f /usr/lib64/libprotobuf.a \
    && rm -f /usr/lib64/libprotoc.a \
    && rm -f /usr/bin/quantlib-test-suite \
    && rm -rf /tmp/3rd_src* \
    && yum clean all

USER root

CMD ["/usr/sbin/init"]
