FROM wusong1024/xone-cplus-dev:v1.0.4
LABEL maintainer="<song.wu@xuncetech.com>" \
      name="xone-cplus-deploy" \
      author="song.wu" \
      version="v1.0.4" \
      systemver="Centos7.5" \
      desc="xone cplus env" \
      build-date="20200429"


RUN echo '/usr/lib/uvframe/' > /etc/ld.so.conf.d/uvframe.conf \
    && echo '/usr/lib/oracle/11.2/client64/lib/' > /etc/ld.so.conf.d/oracle.conf \
    && mkdir -p /home/frame/logs/ \
    && chmod 777 -R /home/frame/ \
    && yum remove devtoolset-7-make devtoolset-7-gcc gcc java cmake3 -y \
    && yum install net-tools telnet perf iproute htop -y \
    && ldconfig
    

USER root


CMD ["/usr/sbin/init"]
