version: "3"
services: 
  xone-gateway-c: 
    image: xone/cplus:v1.0.1
    restart: always
    hostname: xone-gateway-c
    container_name: xone-gateway-c
    command: /usr/bin/uvframe /etc/uvframe/gateway.xml 
    ports:
      - 8062:8062
    volumes:
      - ./config/profile:/home/frame/profile
    privileged: true
    networks:
      - xunce

  xone-mysqlservice:
    image: xone/cplus:v1.0.1
    restart: always
    hostname: xone-mysqlservice
    container_name: xone-mysqlservice
    command: /usr/bin/uvframe /etc/uvframe/mysqlservice.xml
    ports:
      - 8073:8073
    volumes:
      - ./config/profile:/home/frame/profile
    privileged: true
    networks:
      - xunce
      
  xone-basicservice:
    image: xone/cplus:v1.0.1
    restart: always
    hostname: xone-basicservice
    container_name: xone-basicservice
    command: /usr/bin/uvframe /etc/uvframe/basicservice.xml
    ports:
      - 8001:8001
    volumes:
      - ./config/profile:/home/frame/profile
    privileged: true
    networks:
      - xunce
      
  xone-brokerservice:
    image: xone/cplus:v1.0.1
    restart: always
    hostname: xone-brokerservice
    container_name: xone-brokerservice
    command: /usr/bin/uvframe /etc/uvframe/brokerservice.xml
    ports:
      - 8031:8031
      - 8032:8032
    volumes:
      - ./config/profile:/home/frame/profile
    privileged: true
    networks:
      - xunce
 
  xone-orderservice:
    image: xone/cplus:v1.0.1
    restart: always
    hostname: xone-orderservice
    container_name: xone-orderservice
    command: /usr/bin/uvframe /etc/uvframe/orderservice.xml
    ports:
      - 8050:8050
      - 8052:8052
    volumes:
      - ./config/profile:/home/frame/profile
    privileged: true
    networks:
      - xunce
      
  xone-queryservice:
    image: xone/cplus:v1.0.1
    restart: always
    hostname: xone-queryservice
    container_name: xone-queryservice
    command: /usr/bin/uvframe /etc/uvframe/queryservice.xml
    ports:
      - 8851:8851
      - 8853:8853
    volumes:
      - ./config/profile:/home/frame/profile
    privileged: true
    networks:
      - xunce
      
  xone-liquidateservice:
    image: xone/cplus:v1.0.1
    restart: always
    hostname: xone-liquidateservice
    container_name: xone-liquidateservice
    command: /usr/bin/uvframe /etc/uvframe/liquidateservice.xml
    ports:
      - 9527:9527
    volumes:
      - ./config/profile:/home/frame/profile
    privileged: true
    networks:
      - xunce
      
  xone-quantservice:
    image: xone/cplus:v1.0.1
    restart: always
    hostname: xone-quantservice
    container_name: xone-quantservice
    command: /usr/bin/uvframe /etc/uvframe/quantservice.xml
    ports:
      - 8860:8860
    volumes:
      - ./config/profile:/home/frame/profile
    privileged: true
    networks:
      - xunce
networks:
  xunce:
